version: '3.7'
services:
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    container_name: quiz-db
    environment:
      MYSQL_DATABASE: 'quiz-system'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - quiz-db:/var/lib/mysql

volumes:
  quiz-db: